import type { Metadata } from "next";
import "./globals.css";
import Siderbar from "./(dashboard)/_components/sidebar";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  display: "auto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="flex h-full">
          {" "}
          <Siderbar />
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
